<?php

namespace Sepia\Redsys\PaymentRequest;

final class Parameter
{
    const AMOUNT = 'DS_MERCHANT_AMOUNT';
    const CURRENCY = 'DS_MERCHANT_CURRENCY';

    const MERCHANT_ID = 'DS_MERCHANT_IDENTIFIER';
    const MERCHANT_CODE = 'DS_MERCHANT_MERCHANTCODE';
    const MERCHANT_DATA = 'DS_MERCHANT_MERCHANTDATA';
    const MERCHANT_NAME = 'DS_MERCHANT_MERCHANTNAME';

    const CUSTOMER_NAME = 'DS_MERCHANT_TITULAR';

    const TERMINAL = 'DS_MERCHANT_TERMINAL';

    const PAYMENT_METHOD = 'DS_MERCHANT_PAYMETHODS';
    const PAN = 'DS_MERCHANT_PAN';
    const EXPIRY_DATE = 'DS_MERCHANT_EXPIRYDATE';
    const CVV2 = 'DS_MERCHANT_CVV2';
    const ORDER = 'DS_MERCHANT_ORDER';
    const PRODUCT_DESCRIPTION = 'DS_MERCHANT_PRODUCTDESCRIPTION';

    const TRANSACTION_TYPE = 'DS_MERCHANT_TRANSACTIONTYPE';

    const NOTIFICATION_URL = 'DS_MERCHANT_MERCHANTURL';
    const URL_OK = 'DS_MERCHANT_URLOK';
    const URL_KO = 'DS_MERCHANT_URLKO';
    const LANGUAGE = 'DS_MERCHANT_CONSUMERLANGUAGE';
}
